#Install nginx using in yaml format by using ansible-playbook

---
- name: update servers
  hosts: localhost
  become: yes

  tasks:
  - name: Intsall nginx
    copy:
      content: |
        [nginx]
        name=nginx repo
        baseurl=ttps://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck=0
        enabled=1
      dest: /etc/yum.repos.d/nginx.repo

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Start nginx
    yum:
      name: nginx
      state: started

...
